### ISSUE TITLE
tag a new release

### ISSUE THREAD

**Issue by musm** [JuliaIO/LibExpat.jl#62]

**Comment by SimonDanisch** [comment]
Do we have https://github.com/attobot for LibExpat? That would make things easy!
If not, I think I can't activate it :(
@amitmurthy ?

**Comment by musm** [comment]
Would be nice to get attobot installed if it's not already!  We will need to tag since `WinRPM` is failing ... https://github.com/JuliaPackaging/WinRPM.jl/issues/88

I can't figure out the master failures, but I guess that can come later...

**Comment by amitmurthy** [comment]
It has been installed under Integrations. Anything else I need to do?

<img width="776" alt="screen shot 2017-01-11 at 9 35 33 am" src="https://cloud.githubusercontent.com/assets/117461/21835247/7ec258e2-d7e1-11e6-8fe3-1adf0774d593.png">

**Comment by amitmurthy** [comment]
I suspect the master failure is related to https://github.com/JuliaLang/julia/issues/19774
