### ISSUE TITLE
update travis and appveyor for new org

### ISSUE THREAD

**Issue by musm** [JuliaIO/LibExpat.jl#68]
Someone with more privileges will need to configure these.
Not sure if attobot is enabled but we should probably do that too.

**Comment by SimonDanisch** [comment]
Travis seems to be running fine, no?

**Comment by SimonDanisch** [comment]
Attabot seems fine as well. I'm closing for now, if you find this to be incorrect, please reopen :)

**Comment by musm** [comment]
Travis seems to now be up and running but appveyor isn't

**Comment by SimonDanisch** [comment]
....true... of course Appveyor needs special treatment -.- I think I fixed it!
