### ISSUE TITLE
Not precompile safe

### ISSUE THREAD

**Issue by musm** [JuliaIO/LibExpat.jl#77]
Would be good if libexpat is precompile safe

**Comment by stevengj** [comment]
I took a quick glance through the source code, and it seems like the only thing you would have to change would be to make the `cfunction` global variables into local variables.

**Comment by musm** [comment]
That seems to fix things, thanks! I will open a PR.

**Comment by musm** [comment]
PR https://github.com/JuliaIO/LibExpat.jl/pull/83 should address this (feel free to take a look and approve or request changes)
